apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteocli-deployment
  labels:
    app: meteocli
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meteocli
  template:
    metadata:
      labels:
        app: meteocli
    spec:
      containers:
      - name: meteocli
        image: docker.io/lucchoubert/meteocli:0.1
        ports:
        - containerPort: 80
